### ISSUE TITLE
Trouble finding config/app.yml in sinatra app

### ISSUE THREAD

**Issue by soumyaray** [elabs/econfig#14]
I'm creating a Sinatra app at: https://github.com/ISS-SOA/FaceGroupie-API/tree/fb_group_info

An example of my `config/app.yml` is at `config/app.yml.example`

A couple of difficulties I've had:
- Had to add `Econfig.root = File.dirname(__FILE__)` to my `app.rb` or else it complained that `Econfig.root` is not set. Not sure if this was the way to resolve it?
- running my specs (see [group_spec.rb](https://github.com/ISS-SOA/FaceGroupie-API/blob/fb_group_info/spec/group_spec.rb)) and it cannot find any of the variables from my `config/app.yml`.  It has no problem finding environment variables.  What might I be doing wrong here?

Until I find a fix, I'm just going to load `config/app.yml` to ENV myself.

**Comment by soumyaray** [comment]
I've found a solution, but not sure if this is really the way to use econfig for Sinatra.

I have added the following lines on top of my `app.rb`:
```
ENV['RACK_ENV'] ||= 'development'
Econfig.env = ENV['RACK_ENV']
Econfig.root = File.dirname(__FILE__)
```

And I've put `extend Econfig::Shortcut` in my module.

Everything works well now!  One observation (not mentioned in the README): the keys loaded from the yml file are case sensitive, whereas the keys from environment variables are case insensitive.

Please feel free to close this issue if the above is the expected way of using econfig.  Many thanks for this useful gem.

**Comment by jnicklas** [comment]
@soumyaray yes that looks like a reasonable solution. For Rails we do something very similar.

**Comment by soumyaray** [comment]
Thanks @jnicklas -- let me know if you'd like me to take a stab at adding some of this into the README file and issuing a PR.  There is no mention of `Econfig.root` or Econfig.env` in there right now.

**Comment by jnicklas** [comment]
That would be great!
