### ISSUE TITLE
`false` is not a valid value

### ISSUE THREAD

**Issue by elabs-dev** [elabs/econfig#9]
```
MyApp.config[:live] = true
MyApp.config.live # => true
MyApp.config[:live] = false
MyApp.config.live # => Econfig::NotFound: configuration key 'live' is not set
```

This is more or less by design at the moment, considering we raise an error when a key is missing and we can't differentiate a missing value from a `nil` or `false` value.

Perhaps allowing false would be in order, but still treat nil as a missing value?

// @Burgestrand

**Comment by ramhoj** [comment]
Closes 36b49e9b84b2795c3bcc42c522e0b59e406f9b38
